build_pages:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - flutter config --enable-web
    - flutter pub get
  script:
    - cd example
    - flutter build web
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - cd example
    - cp -r build/web ../public
  artifacts:
    paths:
      - public
  only:
    - staging
