name: easel
description: The CustomPaint in a declarative way. We need more precise way to draw something in the canvas.
version: 0.1.0
homepage: https://letyletylety.gitlab.io/easel_by_example/
repository: https://github.com/letyletylety/easel
issue_tracker: https://github.com/letyletylety/easel/issues

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: